/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Annals: typeof import('./src/components/Annals.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppToast: typeof import('./src/components/AppToast.vue')['default']
    Btn: typeof import('./src/components/Btn.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DateControl: typeof import('./src/components/DateControl.vue')['default']
    Init: typeof import('./src/components/Init.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalDiary: typeof import('./src/components/ModalDiary.vue')['default']
    ModalYear: typeof import('./src/components/ModalYear.vue')['default']
    Month: typeof import('./src/components/Month.vue')['default']
    MonthPicker: typeof import('./src/components/MonthPicker.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    Year: typeof import('./src/components/Year.vue')['default']
  }
}
